logging:
  level: DEBUG
  file: 'huey.log'

database:
  host: 'localhost'
  port: 3306
  user: 'username'
  password: 'password'
  database: 'huey_db'

system:
  os: 'debian-bookworm'
  python_version: '3.11'
  virtual_env: '/workspace/venv'
  dependencies:
    - pygpt-net
    - docker
    - kubernetes
    - fastapi
    - redis
