version: "3.8"

services:
  monkey-head-project:
    container_name: Monkey-Head-Project
    build: .
    volumes:
      - C:\Users\GenCore\Desktop\Huey:/workspace  # Mounts your repo inside Docker
    working_dir: /workspace
    tty: true
    stdin_open: true
