apiVersion: v1
kind: PersistentVolume
metadata:
  name: gencore-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/gencore"
  # Ensuring PV is retained even if the PVC is deleted
  persistentVolumeReclaimPolicy: Retain
  # Adding node affinity to ensure PV is created on specific nodes if required
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - your-node-name  # Replace with your specific node name if needed

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gencore-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gencore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gencore
  template:
    metadata:
      labels:
        app: gencore
    spec:
      containers:
      - name: gencore-container
        image: gencore-image:latest  # Update this with the actual name and tag of your Docker image
        ports:
        - containerPort: 4488
        volumeMounts:
        - name: gencore-volume
          mountPath: "/app/data"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        env:
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONUNBUFFERED
          value: "1"
        # Adding liveness and readiness probes for health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 4488
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4488
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: gencore-volume
        persistentVolumeClaim:
          claimName: gencore-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gencore-service
spec:
  selector:
    app: gencore
  ports:
  - protocol: TCP
    port: 4488
    targetPort: 4488
  type: LoadBalancer
  # External traffic policy to ensure network traffic is routed properly
  externalTrafficPolicy: Local
  # Uncomment and set the load balancer IP if you want to set a specific IP
  # loadBalancerIP: 192.168.50.1
  # (NOTE: This content has been written or altered by an AI agent & is pending approval from a human counterpart.)