apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanoosPV
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "V:/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanoosPVC
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanoosDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanoos
  template:
    metadata:
      labels:
        app: nanoos
    spec:
      containers:
      - name: nanoosContainer
        image: nanoos-image:latest  # Update this with the actual name and tag of your Docker image
        ports:
        - containerPort: 5901
        volumeMounts:
        - name: nanoosVolume
          mountPath: "/data"
      volumes:
      - name: nanoosVolume
        persistentVolumeClaim:
          claimName: nanoosPVC

---
apiVersion: v1
kind: Service
metadata:
  name: nanoosService
spec:
  selector:
    app: nanoos
  ports:
  - protocol: TCP
    port: 5901
    targetPort: 5901
  type: LoadBalancer