version: '3.8'

services:
  app:
    container_name: debian-trixie-python
    image: debian:trixie
    entrypoint: [ "/bin/bash", "-c", "--" ]
    command: >
      bash -c "apt update &&
      apt install -y python3.11 python3.11-venv python3.11-dev &&
      python3.11 --version &&
      tail -f /dev/null"
    init: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
